"""These dicts translate between canonical names and non-canonical
(some misspelled, mostly just shorthand).  Because they all have
to match the Vassal name (as that's what the db is generated
from), the Vassal errors dict translates correct keys to the
corresponding incorrect Vassal values, while the listbuilder errors
dict translates incorrect keys to Vassal values regardless of the
correctness of the Vassal value.

"exectuorclass": "executorclass" is a special case because the
reference in the card itself to the ship token is wrong.  I have no
idea why it is able to successfully spawn in-game, but this fixes
it on my side soooo...
"""

# Listbuilder <> Vassal
nomenclature_translation = {
    "7thfleetstardestroyer": "seventhfleetstardestroyer",
    "acclamatori": "acclamatoriclassassaultship",
    "acclamatoriclass": "acclamatoriclassassaultship",
    "acclamatorii": "acclamatoriiclassassaultship",
    "acclamatoriiclass": "acclamatoriiclassassaultship",
    "adartalon": "adartallon",
    "admiralmottiarc": "admiralmotti",
    "admiralozzelcom": "admiralozzel",
    "admiralscreedarc": "admiralscreed",
    "ahsokatanodelta7aetherspritesquadron": "ahsokatanodelta7",
    "ahsokatanooff": "ahsokatano",
    "anakinskywalkerbtlb": "anakinskywalkerbtlbywing",
    "anakinskywalkerbtlbywingsquadron": "anakinskywalkerbtlbywing",
    "anakinskywalkerdelta": "anakinskywalkerdelta7",
    "anakinskywalkerdelta7aetherspritesquadron": "anakinskywalkerdelta7",
    "anakinskywalkertwilightlegacy": "anakinskywalkertwilight",
    "anakinskywalkeryrep": "anakinskywalkerbtlbywing",
    "arc170starfightersquadron": "arc170squadron",
    "armedcruiser": "consularclassarmedcruiser",
    "arquitensclasscommandcruiser": "arquitenscommandcruiser",
    "arquitensclasslightcruiser": "arquitenslightcruiser",
    "arquitensclasslightcruiserarc": "arquitenslightcruisergar",
    "assaultfrigatemk2a": "assaultfrigatemarkiia",
    "assaultfrigatemk2b": "assaultfrigatemarkiib",
    "assaultfrigatemkiia": "assaultfrigatemarkiia",
    "assaultfrigatemkiib": "assaultfrigatemarkiib",
    "axe": "axev19torrent",
    "axev19torrentsquadron": "axev19torrent",
    "bailorgana": "bailorganacom",
    "baktoidprototypes": "baktoidprototypeshyenabomber",
    "baktoidprototypeshyenaclassdroidbombersquadron": "baktoidprototypeshyenabomber",
    "battlerefit": "hardcellclassbattlerefit",
    "belbullab22starfightersquadron": "belbullab22squadron",
    "biggsdarklighter": "biggsdarklighterxwing",
    "biggsdarklighterxwingsquadron": "biggsdarklighterxwing",
    "blacksquadron": "blacksquadrontiefighter",
    "blacksquadrontiefightersquadron": "blacksquadrontiefighter",
    "bltbywingsquadron": "btlbywingsquadron",
    "bobafett": "bobafettslave1",
    "bobafettslavei": "bobafettslave1",
    "bossk": "bosskhoundstooth",
    "captainjonus": "captainjonustiebomber",
    "captainjonustiebombersquadron": "captainjonustiebomber",
    "chargerc70": "consularclasschargerc70retrofit",
    "cienaree": "cienareetieinterceptor",
    "cienareetieinterceptorsquadron": "cienareetieinterceptor",
    "clonecmdrwolffe": "clonecommanderwolffe",
    "coloneljendon": "coloneljendonlambdaclass",
    "coloneljendonlambdaclassshuttle": "coloneljendon",
    "commandersatoarc": "commandersato",
    "commsfrigate": "munificentclasscommsfrigate",
    "consulararmedcruiser": "consularclassarmedcruiser",
    "consularchargerc70": "consularclasschargerc70retrofit",
    "consularclasschargerc70": "consularclasschargerc70retrofit",
    "corranhorn": "corranhornewing",
    "corranhornewingsquadron": "corranhornewing",
    "countdookusithinfiltratorlegacy": "countdookusithinfiltrator",
    "cr90acorvette": "cr90corvettea",
    "cr90bcorvette": "cr90corvetteb",
    "cr90corelliancorvettea": "cr90corvettea",
    "cr90corelliancorvetteb": "cr90corvetteb",
    "daggersquadron": "daggersquadronbwing",
    "daggersquadronbwingsquadron": "daggersquadronbwing",
    "darthmaulscimitarlegacy": "darthmaulscimitar",
    "darthvaderarc": "darthvadercom",
    "darthvaderdefender": "darthvadertiedefender",
    "darthvadertieadvancedsquadron": "darthvadertieadvanced",
    "darthvadertieadvancedsquadronarc": "darthvadertieadvanced",
    "darthvadertiedefendersquadron": "darthvadertiedefender",
    "dashrendar": "dashrendaroutrider",
    "daultaydofinelegacy": "daultaydofine",
    "dbs404": "dbs404hyenabomber",
    "dbs404hyenaclassdroidbombersquadron": "dbs404hyenabomber",
    "dby827heavyturbolaser": "dby827heavyturbolasers",
    "dengar": "dengarpunishingone",
    "dfs311": "dfs311vulturedroid",
    "dfs311vultureclassdroidfightersquadron": "dfs311vulturedroid",
    "dgs047hmpdroidgunshiplegacy": "dgs047hmpdroidgunship",
    "dist81droidtrifightersquadron": "distb1droidtrifighter",
    "distb1": "distb1droidtrifighter",
    "dutchvander": "dutchvanderywing",
    "dutchvanderywingsquadron": "dutchvanderywing",
    "emperorpalpatinearc": "emperorpalpatinecom",
    "exectuorclass": "executorclass",
    "executoriclassstardreadnought": "executoristardn",
    "executoriiclassstardreadnought": "executoriistardn",
    "fennraumandaloriangauntletfighter": "fennraugauntletfighter",
    "fivesevenlaatigunshiplegacy": "fivesevenlaatigunship",
    "g9riggerclassfreighterlegacy": "g9riggerclassfreighter",
    "gammasquadron": "gammasquadrontiebomber",
    "gammasquadrontiebombersquadron": "gammasquadrontiebomber",
    "garmbeliblisarc": "garmbeliblis",
    "garsaxon": "garsaxongauntletfighter",
    "garsaxonmandaloriangauntletfighter": "garsaxongauntletfighter",
    "generaldravenarc": "generaldravencom",
    "generalgrievous": "generalgrievousbelbullab22",
    "generalgrievousbelbullab22starfightersquadron": "generalgrievousbelbullab22",
    "genericritrcommander": "admiralkonstantine",
    "gladiatoriclassstardestroyer": "gladiatori",
    "gladiatoriiclassstardestroyer": "gladiatorii",
    "goldsquadron": "goldsquadronywing",
    "goldsquadronywingsquadron": "goldsquadronywing",
    "gozanticlassassaultcarriers": "gozantiassaultcarriers",
    "gozanticlasscruisers": "gozanticruisers",
    "gozanticlasscruiserscis": "gozanticruiserscis",
    "greensquadron": "greensquadronawing",
    "greensquadronawing": "greensquadron",
    "greensquadronawingsquadron": "greensquadron",
    "hansolo": "hansolomillenniumfalcon",
    "hansolomillenniumfalconarc": "hansolomillenniumfalcon",
    "haorchallprototypes": "haorchallprototypesvulturedroid",
    "haorchallprototypesvultureclassdroidfightersquadron": "haorchallprototypesvulturedroid",
    "hardcellbattlerefit": "hardcellclassbattlerefit",
    "hardcelltransport": "hardcellclasstransport",
    "hardendbulkheads": "hardenedbulkheads",
    "hmpdroidgunshiplegacy": "hmpdroidgunship",
    "hondoohnakaslavei": "hondoohnakaslave1",
    "howlrunner": "howlrunnertiefighter",
    "howlrunnertiefightersquadron": "howlrunnertiefighter",
    "hwk290": "hwk290lightfreighter",
    "hyenaclassdroidbombersquadron": "hyenabombersquadron",
    "hyenadroidbombersquadron": "hyenabombersquadron",
    "ig88": "ig88ig2000",
    "ig88b": "ig88big2000b",
    "imperialiclassstardestroyer": "imperiali",
    "imperialiiclassstardestroyer": "imperialii",
    "imperialstardestroyercymoon1refit": "cymoon1refit",
    "imperialstardestroyerkuatrefit": "kuatrefit",
    "independence": "independance",
    "interdictorclasscombatrefit": "interdictorcombatrefit",
    "interdictorclasssuppressionrefit": "interdictorsuppressionrefit",
    "interdictorcombatrefitarc": "interdictorcombatrefit",
    "isdcymoon1refit": "cymoon1refit",
    "isdkuatrefit": "kuatrefit",
    "jangofett": "jangofettmodifiedfirespray31",
    "jangofettslave1": "jangofettmodifiedfirespray31",
    "jangofettslavei": "jangofettmodifiedfirespray31",
    "janors": "janorsmoldycrow",
    "kananjarrus": "kananjarrushwk290",
    "ketsuonyo": "ketsuonyoshadowcaster",
    "keyanfarlander": "keyanfarlanderbwing",
    "keyanfarlanderbwingsquadron": "keyanfarlanderbwing",
    "kiadimundilegacy": "kiadimundi",
    "kickback": "kickbackv19torrent",
    "kickbackv19torrentsquadron": "kickbackv19",
    "kitfisto": "kitfistodelta7",
    "kitfistodelta7aetherspritesquadron": "kitfistodelta7",
    "kyrstaagatecom": "kyrstaagate",
    "laatigunshiplegacy": "laati",
    "lambdashuttle": "lambdaclassshuttle",
    "lancerpursuitcraft": "lancerclasspursuitcraft",
    "landocalrissianoff": "landocalrissian",
    "landocarissian": "landocalrissian",
    "leiaorganaarc": "leiaorganacom",
    "lietenantblount": "lieutenantblount",
    "lieutenantblount": "lieutenantblountz95",
    "lieutenantblountz95headhuntersquadron": "lieutenantblount",
    "linkedturbolaserturrets": "linkedturbolasertowers",
    "locationfirecontrol": "localfirecontrol",
    "lukeskywalker": "lukeskywalkerxwing",
    "lukeskywalkerxwingsquadron": "lukeskywalkerxwing",
    "lukeskywalkerxwingsquadronarc": "lukeskywalkerxwing",
    "luminaraundulidelta7aetherspritesquadron": "luminaraundulidelta7",
    "maareksteele": "maarekstele",
    "maarekstele": "maareksteletiedefender",
    "maareksteletiedefendersquadron": "maareksteletiedefender",
    "majorrhymer": "majorrhymertiebomber",
    "majorrhymertiebombersquadron": "majorrhymertiebomber",
    "maleehurra": "maleehurrascurrgh6",
    "maleehurrascurrgh6bomber": "maleehurrascurrgh6",
    "mandaloriangauntletfighter": "mandogauntletfighter",
    "martmattin": "martmattinsatoshammer",
    "matchstickbtlbywingsquadron": "matchstickbtlbywing",
    "maulermithel": "maulermitheltiefighter",
    "maulermitheltiefightersquadron": "maulermitheltiefighter",
    "modifiedpeltaclassassaultship": "peltaclassassaultship",
    "modifiedpeltaclassassaultshiparc": "peltaclassassaultship",
    "modifiedpeltaclasscommandship": "peltaclasscommandship",
    "moncalamariexodusfleet": "moncalexodusfleet",
    "monmothmaarc": "monmothma",
    "moraloeval": "moraloevalyv666",
    "mornakee": "mornakeevt49decimator",
    "munificentclasscommandfrigatearc": "munificentclasscommandfrigate",
    "munificentcommsfrigate": "munificentclasscommsfrigate",
    "munificentstarfrigate": "munificentclassstarfrigate",
    "munitionsresuppy": "munitionsresupply",
    "norrawexley": "norrawexleyywing",
    "norrawexleyywingsquadron": "norrawexleyywing",
    "nym": "nymhavoc",
    "obiwankenobi": "obiwankenobicom",
    "oddball": "oddballarc170",
    "oddballarc170starfightersquadron": "oddballarc170",
    "onagerstardestroyer": "onagerclassstardestroyer",
    "onagertestbed": "onagerclasstestbed",
    "partsresuppy": "partsresupply",
    "peltaassaultship": "peltaclassassaultship",
    "peltacommandship": "peltaclasscommandship",
    "peltamedicalfrigate": "peltaclassmedicalfrigate",
    "peltatransportfrigate": "peltaclasstransportfrigate",
    "phlacarphoccprototypes": "phlacarphoccprototypesdroidtrifighter",
    "phlacarphoccprototypesdroidtrifightersquadron": "phlacarphoccprototypesdroidtrifighter",
    "plokoon": "plokoondelta7",
    "plokoondelta7aetherspritesquadron": "plokoondelta7",
    "providenceclasscarrier": "providencecarrier",
    "providenceclasscarrierreb": "providencecarrierreb",
    "providenceclassdreadnought": "providencedreadnought",
    "quarrenprototypegunshiparc": "quarrenprototypegunship",
    "quasarfireiclasscruisercarrier": "quasarfirei",
    "quasarfireiiclasscruisercarrier": "quasarfireii",
    "r2d2twilightlegacy": "r2d2twilight",
    "raidericlasscorvette": "raideri",
    "raideriiclasscorvette": "raiderii",
    "rayantilles": "raymusantilles",
    "recusantclasslightdestroyer": "recusantlightdestroyer",
    "recusantclasssupportdestroyer": "recusantsupportdestroyer",
    "roguesquadron": "roguesquadronxwing",
    "roguesquadronxwingsquadron": "roguesquadronxwing",
    "sabersquadron": "sabersquadrontieinterceptor",
    "sabersquadrontieinterceptorsquadron": "sabersquadrontieinterceptor",
    "sharabey": "sharabeyawing",
    "sharabeyawingsquadron": "sharabeyawing",
    "solorcorona": "solarcorona",
    "soontirfel": "soontirfeltieinterceptor",
    "soontirfeltieinterceptorsquadron": "soontirfeltieinterceptor",
    "ssdassaultprototype": "stardnassaultprototype",
    "ssdcommandprototype": "stardncommandprototype",
    "ssdexecutori": "executoristardn",
    "ssdexecutorii": "executoriistardn",
    "starcourierlegacy": "starcourier",
    "stardreadnoughtassaultprototype": "stardnassaultprototype",
    "stardreadnoughtcommandprototype": "stardncommandprototype",
    "starfrigate": "munificentclassstarfrigate",
    "starhawkbattleshipmarki": "starhawkmarki",
    "starhawkbattleshipmarkii": "starhawkmarkii",
    "starhawkclassbattleshipmarki": "starhawkmarki",
    "starhawkclassbattleshipmarkii": "starhawkmarkii",
    "starhawkclassmki": "starhawkmarki",
    "starhawkclassmkii": "starhawkmarkii",
    "supriseattack": "surpriseattack",
    "teltrevura": "teltrevurajumpmaster",
    "teltrevurajumpmaster5000": "teltrevurajumpmaster",
    "tempestsquadron": "tempestsquadrontieadvanced",
    "tempestsquadrontieadvancedsquadron": "tempestsquadrontieadvanced",
    "tennumb": "tennumbbwing",
    "tennumbbwingsquadron": "tennumbbwing",
    "transport": "hardcellclasstransport",
    "tychocelchu": "tychocelchuawing",
    "tychocelchuawingsquadron": "tychocelchuawing",
    "valenrudor": "valenrudortiefighter",
    "valenrudortiefightersquadron": "valenrudortiefighter",
    "vcx100freighter": "vcx100lightfreighter",
    "venatoriclassstardestroyer": "venatori",
    "venatoriiclassstardestroyer": "venatorii",
    "venatoriiclassstardestroyerimp": "venatoriiimp",
    "venatoriiclassstardestroyerimperial": "venatoriiimp",
    "venatorstardestroyerimperatorrefit": "venatorimperatorrefit",
    "venatorstardestroyerimperatorrefitarc": "venatorimperatorrefit",
    "victoryiclassstardestroyer": "victoryi",
    "victoryiclassstardestroyergar": "victoryigar",
    "victoryiiclassstardestroyer": "victoryii",
    "vultskerristieinterceptorsquadron": "vultskerristieinterceptor",
    "vultureclassdroidfightersquadron": "vulturedroidsquadron",
    "vulturedroidfightersquadron": "vulturedroidsquadron",
    "wattamborbelbullab22starfightersquadron": "wattamborbelbullab22",
    "wedgeantillesxwingsquadron": "wedgeantillesxwing",
    "whisper": "whispertiephantom",
    "whispertiephantomsquadron": "whispertiephantom",
    "x17turbolasers": "xi7turbolasers",
    "xcustomcommander": "admiralkonstantine",
    "yt1300": "yt1300lightfreighter",
    "yt2400": "yt2400lightfreighter",
    "yv666": "yv666lightfreighter",
    "zertikstrom": "zertikstromtieadvanced",
    "zertikstromtieadvancedsquadron": "zertikstromtieadvanced",
}

""" This dict pairs names of identically-named cards (Darth Vader, Leia Organa,
    etc) with their costs in a tuple (the key) to reference their Vassal name and 
    card type.
"""

ambiguous_names = {
    ("admiralozzel", "20"): ("admiralozzel", "upgrade"),
    ("admiralozzel", "2"): ("admiralozzeloff", "upgrade"),
    ("ahsokatano", "23"): ("ahsokatanodelta7", "squadron"),
    ("ahsokatano", "2"): ("ahsokatano", "upgrade"),
    ("ahsokatano", "6"): ("ahsokatanorepoff", "upgrade"),
    ("ahsokatano", "23"): ("ahsokatanodelta7", "squadron"),
    ("anakinskywalker", "18"): ("anakinskywalkerbtlbywing", "squadron"),
    ("anakinskywalker", "24"): ("anakinskywalkerdelta7", "squadron"),
    ("anakinskywalker", "27"): ("anakinskywalkercom", "upgrade"),
    ("darthvader", "34"): ("darthvadercom", "upgrade"),
    ("darthvader", "28"): ("darthvadercom", "upgrade"),
    ("darthvader", "3"): ("darthvaderwpn", "upgrade"),
    ("darthvader", "4"): ("darthvaderoff", "upgrade"),
    ("darthvader", "21"): ("darthvadertieadvanced", "squadron"),
    ("darthvader", "25"): ("darthvadertiedefender", "squadron"),
    ("emperorpalpatine", "35"): ("emperorpalpatinecom", "upgrade"),
    ("emperorpalpatine", "32"): ("emperorpalpatinecom", "upgrade"),
    ("emperorpalpatine", "3"): ("emperorpalpatineoff", "upgrade"),
    ("generaldraven", "28"): ("generaldravencom", "upgrade"),
    ("generaldraven", "22"): ("generaldravencom", "upgrade"),
    ("generaldraven", "3"): ("generaldraven", "upgrade"),
    ("generalgrievous", "20"): ("generalgrievouscom", "upgrade"),
    ("generalgrievous", "22"): ("generalgrievousbelbullab22", "squadron"),
    ("gozanticruisers", "24"): ("gozanticruiserscis", "shipcard"),
    ("gozanticruisers", "23"): ("gozanticruiser", "shipcard"),
    ("herasyndulla", "28"): ("herasyndullaghost", "squadron"),
    ("herasyndulla", "23"): ("herasyndullaxwing", "squadron"),
    ("hondoohnaka", "24"): ("hondoohnakaslave1", "squadron"),
    ("hondoohnaka", "2"): ("hondoohnaka", "upgrade"),
    ("kyrstaagate", "25"): ("kyrstaagate", "upgrade"),
    ("kyrstaagate", "5"): ("kyrstaagateoff", "upgrade"),
    ("landocalrissian", "24"): ("landocalrissianmillenniumfalcon", "squadron"),
    ("landocalrissian", "4"): ("landocalrissian", "upgrade"),
    ("leiaorgana", "28"): ("leiaorganacom", "upgrade"),
    ("leiaorgana", "3"): ("leiaorganaoff", "upgrade"),
    ("luminaraunduli", "23"): ("luminaraundulidelta7", "squadron"),
    ("luminaraunduli", "25"): ("luminaraundulicom", "upgrade"),
    ("plokoon", "26"): ("plokooncom", "upgrade"),
    ("plokoon", "24"): ("plokoondelta7", "squadron"),
    ("providenceclasscarrier", "95"): ("providencecarrierreb", "shipcard"),
    ("providenceclasscarrier", "102"): ("providencecarrier", "shipcard"),
    ("victoryiclassstardestroyer", "73"): ("victoryi", "shipcard"),
    ("victoryiclassstardestroyer", "75"): ("victoryigar", "shipcard"),
    ("wattambor", "5"): ("wattambor", "upgrade"),
    ("wattambor", "20"): ("wattamborbelbullab22", "squadron"),
    ("wedgeantilles", "19"): ("wedgeantillesxwing", "squadron"),
    ("wedgeantilles", "4"): ("wedgeantillesoff", "upgrade"),
}
